import React, { useState } from 'react';
import {
  X,
  Copy,
  Check,
  Download,
  FileText,
  Table,
  FileCode,
  Printer,
  Sparkles,
  ExternalLink
} from 'lucide-react';
import { StudyPlan } from '../types';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  plan: StudyPlan;
}

export type ExportFormat = 'markdown' | 'text' | 'csv' | 'json';

// Helper to convert plan into structured Markdown format
export function generatePlanMarkdown(plan: StudyPlan): string {
  const sanitizedSubject = plan.subject || 'Study Plan';
  return `# 📚 Study Timetable: ${sanitizedSubject}

> **Generated by AI College Student Assistant Agent**
> Subject: **${sanitizedSubject}** | Target Exam: **${plan.examDate || 'Not specified'}**
> Total Commitment: **${plan.daysCount} Days** (${plan.dailyHours} Hours/Day) | Level: **${plan.knowledgeLevel || 'Intermediate'}**
> Preferred Time: **${plan.preferredStudyTime || 'Anytime'}** | Progress: **${plan.progress || 0}% Completed**

---

## 📅 Daily Study Schedule

${plan.schedule
  .map(
    (day) => `### 🗓️ Day ${day.day}: ${day.date} [Priority: ${day.priority}]
- **Duration:** ${day.duration}
- **Status:** ${day.completed ? '[x] Completed' : '[ ] In Progress / Pending'}

#### 📖 Topics to Master
${day.topics.map((t) => `- [${day.completed ? 'x' : ' '}] ${t}`).join('\n')}

#### ✍️ Practice & Problem Sets
${day.practiceTasks.map((p) => `- [${day.completed ? 'x' : ' '}] ${p}`).join('\n')}

#### 🧠 Active Revision (${day.revisionTime})
- Review formula derivations and flashcards for Day ${day.day} topics.

#### ☕ Break & Mental Wellness Strategy
- ${day.breakSuggestions}
`
  )
  .join('\n---\n\n')}

---
*Created with AI Student Assistant. Good luck with your preparation!*
`;
}

// Helper to convert plan into clean Plain Text / Outline
export function generatePlanPlainText(plan: StudyPlan): string {
  const sanitizedSubject = plan.subject || 'Study Plan';
  const divider = '='.repeat(60);
  const subDivider = '-'.repeat(60);

  return `${divider}
AI STUDY PLANNER - TIMETABLE
Subject: ${sanitizedSubject}
Commitment: ${plan.daysCount} Days @ ${plan.dailyHours} Hours/Day
Target Exam Date: ${plan.examDate || 'Not specified'}
Knowledge Level: ${plan.knowledgeLevel || 'Intermediate'}
Preferred Study Slot: ${plan.preferredStudyTime || 'Anytime'}
Overall Progress: ${plan.progress || 0}%
${divider}

SCHEDULE BREAKDOWN:

${plan.schedule
  .map(
    (day) => `[DAY ${day.day}] ${day.date}
Priority: ${day.priority} | Duration: ${day.duration} | Status: ${day.completed ? '[COMPLETED]' : '[PENDING]'}

TOPICS TO COVER:
${day.topics.map((t) => `  * ${t}`).join('\n')}

PRACTICE & DERIVATIONS:
${day.practiceTasks.map((p) => `  * ${p}`).join('\n')}

ACTIVE REVISION:
  ${day.revisionTime}

BREAK STRATEGY:
  ${day.breakSuggestions}
`
  )
  .join(`\n${subDivider}\n\n`)}
${divider}
`;
}

// Helper to convert plan into standard CSV format for Excel/Sheets/Notion
export function generatePlanCSV(plan: StudyPlan): string {
  const headers = [
    'Day',
    'Date',
    'Priority',
    'Duration',
    'Status',
    'Topics',
    'Practice Tasks',
    'Revision Time',
    'Break Strategy'
  ];

  const escapeCSV = (val: string) => {
    const escaped = (val || '').replace(/"/g, '""');
    return `"${escaped}"`;
  };

  const rows = plan.schedule.map((day) => [
    escapeCSV(`Day ${day.day}`),
    escapeCSV(day.date),
    escapeCSV(day.priority),
    escapeCSV(day.duration),
    escapeCSV(day.completed ? 'Completed' : 'Pending'),
    escapeCSV(day.topics.join('; ')),
    escapeCSV(day.practiceTasks.join('; ')),
    escapeCSV(day.revisionTime),
    escapeCSV(day.breakSuggestions)
  ]);

  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\r\n');
}

// Helper to convert plan into pretty JSON
export function generatePlanJSON(plan: StudyPlan): string {
  return JSON.stringify(plan, null, 2);
}

export const StudyPlanExportModal: React.FC<Props> = ({ isOpen, onClose, plan }) => {
  const [selectedFormat, setSelectedFormat] = useState<ExportFormat>('markdown');
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null);

  if (!isOpen) return null;

  const currentContent = (() => {
    switch (selectedFormat) {
      case 'markdown':
        return generatePlanMarkdown(plan);
      case 'text':
        return generatePlanPlainText(plan);
      case 'csv':
        return generatePlanCSV(plan);
      case 'json':
        return generatePlanJSON(plan);
    }
  })();

  const copyToClipboard = async (text: string, formatLabel: string) => {
    try {
      if (navigator.clipboard && window.isSecureContext) {
        await navigator.clipboard.writeText(text);
      } else {
        const textArea = document.createElement('textarea');
        textArea.value = text;
        textArea.style.position = 'fixed';
        textArea.style.left = '-999999px';
        textArea.style.top = '-999999px';
        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();
        document.execCommand('copy');
        textArea.remove();
      }
      setCopiedFormat(formatLabel);
      setTimeout(() => setCopiedFormat(null), 2200);
    } catch (err) {
      console.error('Failed to copy to clipboard', err);
    }
  };

  const handleDownload = () => {
    const filenamePrefix = (plan.subject || 'Study_Plan').replace(/[^a-zA-Z0-9_-]/g, '_');
    let filename = '';
    let mimeType = '';

    switch (selectedFormat) {
      case 'markdown':
        filename = `${filenamePrefix}_Plan.md`;
        mimeType = 'text/markdown;charset=utf-8';
        break;
      case 'text':
        filename = `${filenamePrefix}_Plan.txt`;
        mimeType = 'text/plain;charset=utf-8';
        break;
      case 'csv':
        filename = `${filenamePrefix}_Timetable.csv`;
        mimeType = 'text/csv;charset=utf-8';
        break;
      case 'json':
        filename = `${filenamePrefix}_Data.json`;
        mimeType = 'application/json;charset=utf-8';
        break;
    }

    const blob = new Blob([currentContent], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  const formatsConfig: {
    id: ExportFormat;
    name: string;
    ext: string;
    icon: React.ReactNode;
    desc: string;
  }[] = [
    {
      id: 'markdown',
      name: 'Markdown',
      ext: '.md',
      icon: <FileText className="w-4 h-4" />,
      desc: 'Interactive checklists & formatted headers for Notion, Obsidian, and GitHub'
    },
    {
      id: 'text',
      name: 'Plain Text',
      ext: '.txt',
      icon: <FileText className="w-4 h-4" />,
      desc: 'Clean ASCII structured timetable for scratchpads, messaging, or quick printing'
    },
    {
      id: 'csv',
      name: 'Spreadsheet (CSV)',
      ext: '.csv',
      icon: <Table className="w-4 h-4" />,
      desc: 'Tabular layout for Google Sheets, Microsoft Excel, or Numbers'
    },
    {
      id: 'json',
      name: 'JSON Data',
      ext: '.json',
      icon: <FileCode className="w-4 h-4" />,
      desc: 'Structured raw data representation for calendar sync, scripts, or backups'
    }
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs transition-opacity animate-in fade-in duration-200">
      <div
        className="relative w-full max-w-3xl max-h-[90vh] bg-white dark:bg-stone-900 rounded-2xl border border-stone-200 dark:border-stone-800 shadow-2xl flex flex-col overflow-hidden text-stone-900 dark:text-stone-100"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-stone-200 dark:border-stone-800 bg-stone-50/70 dark:bg-stone-850/70">
          <div className="flex items-center gap-2.5">
            <span className="p-2 rounded-xl bg-indigo-50 dark:bg-indigo-950/70 text-indigo-600 dark:text-indigo-400">
              <Download className="w-5 h-5" />
            </span>
            <div>
              <h2 className="text-base font-bold text-stone-900 dark:text-white flex items-center gap-2">
                Export & Share Study Timetable
                <span className="text-[11px] font-normal px-2 py-0.5 rounded-md bg-indigo-100 dark:bg-indigo-900/60 text-indigo-700 dark:text-indigo-300">
                  {plan.subject}
                </span>
              </h2>
              <p className="text-xs text-stone-500 dark:text-stone-400">
                Download your personalized plan in structured format or copy directly to clipboard.
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-stone-400 hover:text-stone-700 dark:hover:text-stone-200 hover:bg-stone-100 dark:hover:bg-stone-800 transition-colors"
            aria-label="Close modal"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-5">
          {/* Format Selector Pills */}
          <div>
            <label className="block text-xs font-semibold text-stone-700 dark:text-stone-300 mb-2">
              Select Output Format:
            </label>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
              {formatsConfig.map((fmt) => {
                const isActive = selectedFormat === fmt.id;
                return (
                  <button
                    key={fmt.id}
                    type="button"
                    onClick={() => setSelectedFormat(fmt.id)}
                    className={`flex flex-col items-start p-3 rounded-xl border text-left transition-all ${
                      isActive
                        ? 'bg-indigo-50/80 dark:bg-indigo-950/50 border-indigo-500 dark:border-indigo-400 shadow-xs'
                        : 'bg-white dark:bg-stone-850 border-stone-200 dark:border-stone-800 hover:border-stone-300 dark:hover:border-stone-700'
                    }`}
                  >
                    <div className="flex items-center justify-between w-full mb-1">
                      <span
                        className={`p-1 rounded-md ${
                          isActive
                            ? 'text-indigo-600 dark:text-indigo-400'
                            : 'text-stone-400 dark:text-stone-500'
                        }`}
                      >
                        {fmt.icon}
                      </span>
                      <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-stone-100 dark:bg-stone-800 text-stone-500 dark:text-stone-400">
                        {fmt.ext}
                      </span>
                    </div>
                    <span className="text-xs font-bold text-stone-900 dark:text-white">
                      {fmt.name}
                    </span>
                    <span className="text-[11px] text-stone-500 dark:text-stone-400 line-clamp-2 mt-0.5 leading-snug">
                      {fmt.desc}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Quick action bar */}
          <div className="flex flex-wrap items-center justify-between gap-3 p-3.5 rounded-xl bg-stone-50 dark:bg-stone-850 border border-stone-200 dark:border-stone-800">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-indigo-600 dark:text-indigo-400 shrink-0" />
              <span className="text-xs text-stone-600 dark:text-stone-300">
                Ready to export: <strong>{plan.schedule.length} Days</strong> of structured study items.
              </span>
            </div>

            <div className="flex items-center gap-2">
              {/* Copy Button */}
              <button
                type="button"
                onClick={() => copyToClipboard(currentContent, selectedFormat)}
                className="px-3 py-1.5 text-xs font-semibold rounded-lg bg-stone-100 dark:bg-stone-800 hover:bg-stone-200 dark:hover:bg-stone-700 text-stone-800 dark:text-stone-200 flex items-center gap-1.5 transition-colors"
              >
                {copiedFormat === selectedFormat ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
                    <span className="text-emerald-700 dark:text-emerald-400">Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5 text-stone-500 dark:text-stone-400" />
                    <span>Copy to Clipboard</span>
                  </>
                )}
              </button>

              {/* Download File Button */}
              <button
                type="button"
                onClick={handleDownload}
                className="px-3 py-1.5 text-xs font-semibold rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white flex items-center gap-1.5 transition-colors shadow-xs"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download File</span>
              </button>

              {/* Print Button */}
              <button
                type="button"
                onClick={handlePrint}
                className="px-2.5 py-1.5 text-xs font-medium rounded-lg border border-stone-300 dark:border-stone-700 hover:bg-stone-100 dark:hover:bg-stone-800 text-stone-700 dark:text-stone-300 flex items-center gap-1 transition-colors"
                title="Print Timetable"
              >
                <Printer className="w-3.5 h-3.5" />
                <span className="hidden sm:inline">Print</span>
              </button>
            </div>
          </div>

          {/* Live Preview Area */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <span className="text-xs font-semibold text-stone-700 dark:text-stone-300">
                Structured Content Preview:
              </span>
              <span className="text-[11px] text-stone-400 font-mono">
                {currentContent.split('\n').length} lines &bull; {currentContent.length} characters
              </span>
            </div>
            <pre className="w-full max-h-64 p-4 text-xs font-mono bg-stone-900 text-stone-100 dark:bg-stone-950 dark:text-stone-200 rounded-xl overflow-x-auto overflow-y-auto border border-stone-800 leading-relaxed select-all">
              {currentContent}
            </pre>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-6 py-3 border-t border-stone-200 dark:border-stone-800 bg-stone-50/70 dark:bg-stone-850/70 text-xs text-stone-500">
          <span>Tip: Markdown output can be pasted directly into Notion, Obsidian, or GitHub gists.</span>
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg border border-stone-300 dark:border-stone-700 hover:bg-stone-100 dark:hover:bg-stone-800 text-stone-700 dark:text-stone-300 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
